services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y" # Required for SQL Server to start
      SA_PASSWORD: "YourPassword123!" # Strong password required
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourPassword123!' -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - "1433:1433" # Expose the SQL Server port
    volumes:
      - database_data:/var/opt/mssql # Persist data to avoid losing it when the container is restarted


volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
